import Layout from '@/components/Layout'
import '../../styles/globals.css'

export const metadata = {
  title: 'Dentis App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="bg-bg">
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
